version: "3.9"

services:
  users:
    build: ./users
    ports:
      - "8001:8000"

  orders:
    build: ./orders
    ports:
      - "8002:8000"
    environment:
      - USERS_URL=http://users:8000
      # AMQP_URL спеціально НЕ задається

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - ORDERS_URL=http://orders:8000
